  title: "Ext Figure 8 D"
output: html_notebook
---
####################################################################################################
## This script contains the code to reproduce Ext Figure 8D                                       ##
## Mensah & Niskanen et al.                                                                       ##
## Aberrant phase separation and nucleolar dysfunction can underlie rare genetic diseases 2023    ##
## Author: Alexandre P Magalhaes                                                                  ##
####################################################################################################

```{r}

library(tidyverse)
library(ggplotgui)
library(ggpubr)

```
```{r}
df <- read_csv("Go_figure.csv")
#df$order <- factor(df$order, levels = df$order[order(df$order)])
df$source <- factor(df$source, levels = c("GO:MF", "GO:CC", "GO:BP"))
names (df)
```


```{r}
Color = c("#dc3912", "#109618", "#ff9900")
g <- ggplot(df, aes(x=negative_log10_of_adjusted_p_value, y=term_name, color=source)) + 
geom_point(aes(size=3)) +
  #scale_size_continuous(limits = c(0, 60), range = c(1,15), breaks = c(0,10,20,30,40,50,60))+
  facet_grid(. ~ Type, scales="free") +
	labs(
		size="Gene number",
		x="log10pvalue",
		y="GO Term",
		title="GO enrichment") +
	theme_bw()+
  scale_y_discrete(limits = rev(levels(df$term_name))) +
  scale_color_manual(values=Color)
g

```

