---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

###########################################################################################
## This script contains the code to reproduce Sup Figure 2                            ##
## Mensah & Niskanen et al.                                                              ##
## Aberrant phase separation and nucleolar dysfunction in human genetic disease 2022     ##
## Author: Alexandre P Magalhaes                                                         ##
###########################################################################################

```{r message=FALSE, warning=FALSE, include=FALSE}

library("tidyverse")
library("ggplotgui")
library("plotly")
library("gridExtra")
library("RColorBrewer")
library("ggpubr")
library("gghighlight")
library("ggrepel")
library("cowplot")
library("viridis")
theme_set(theme_bw())
stringsAsFactors = FALSE
```

```{r}
dfFSVAR <- read_csv('MasterTable_wNMD_wVariantDisease_wRK_WHidrophobic_wNLS_wTransmembrane_220608_Full.csv')
dfFSVAR$DELTA_FullLength <- -1*(dfFSVAR$DELTA_FullLength)
dfFSVAR$DELTA_IDRLength <- -1*(dfFSVAR$DELTA_IDRLength)
dfFSVAR$vestlog10pv <- -log10(dfFSVAR$VEST_pvalue)
dfFS <- dfFSVAR %>% filter (seqTypeExp == "Frameshift")
dfFS <- dfFS[order(dfFS$Pathogenic,decreasing=F),]
dfFS2 <- dfFSVAR %>% filter (seqTypeExp == "Frameshift") %>% filter(PFSseqLength >= 20)
dfFS3 <- dfFSVAR %>% filter (seqTypeExp == "Frameshift") %>% filter(PFSseqLength >= 20) %>% filter(PFSfrac_R >= 0.15) 

dfFS2 <- dfFS2[order(dfFS2$Pathogenic,decreasing=F),]
dfFSH <- dfFSVAR%>% filter (Target == TRUE)


```

```{r}
dfFS$PFSfrac_K <- dfFS$PFSfrac_RK - dfFS$PFSfrac_R
dfFS2$PFSfrac_K <- dfFS2$PFSfrac_RK - dfFS2$PFSfrac_R
dfFS2$WTPFSfrac_K <- dfFS2$WTPFSfrac_RK - dfFS2$WTPFSfrac_R
dfFSH$PFSfrac_K <- dfFSH$PFSfrac_RK - dfFSH$PFSfrac_R
dfFSH$WTPFSfrac_K <- dfFSH$WTPFSfrac_RK - dfFSH$WTPFSfrac_R

dfFSH$PFSfrac_K[dfFSH$PFSfrac_K<0] <- 0
dfFSH$WTPFSfrac_K[dfFSH$WTPFSfrac_K<0] <- 0

dfFS$PFSfrac_K[dfFS$PFSfrac_K<0] <- 0

dfFS2$PFSfrac_K[dfFS2$PFSfrac_K<0] <- 0
dfFS2$WTPFSfrac_K[dfFS2$WTPFSfrac_K<0] <- 0

```

```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSFracPos", y = "PFSFracPos",
           size = 0.5,
            show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of positive aa",
           ylab = "Mut Fraction of positive aa") +
    geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2, show.legend = F,show.legend.text = F) +
    xlim(0, 0.6) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction of positive aa.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSfrac_R", y = "PFSfrac_R",
           size = 0.5,
           show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of Arginine",
           ylab = "Mut Fraction of Arginine") +
    geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 0.6) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction of Arginine.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSfrac_acidic", y = "PFSfrac_acidic",
           size = 0.5,
           show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of acidic aa",
           ylab = "Mut Fraction of acidic aa") +
    geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 0.6) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction of acidic aa.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSfrac_aromatic", y = "PFSfrac_aromatic",
           size = 0.5,
           show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of aromatic residues",
           ylab = "Mut Fraction of aromatic residues") +
    geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 0.4) + 
  ylim(0, 0.4) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction of aromatic residues.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSFracNeg", y = "PFSFracNeg",
           size = 0.5,
           show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of Negative aa",
           ylab = "Mut Fraction of Negative aa") +
    geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 0.6) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction of Negative aa.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSFracDisoPromoting", y = "PFSFracDisoPromoting",
           size = 0.5,
           show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction Disorder Promoting aa",
           ylab = "Mut Fraction Disorder Promoting aa") +
    geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0.2, 1) + 
  ylim(0.2, 1) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction Disorder Promoting aa.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSfrac_L", y = "PFSfrac_L",
           size = 0.5,
           show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of Leucine",
           ylab = "Mut Fraction of Leucine") +
  geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 0.4) + 
  ylim(0, 0.4) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction of Leucine.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSfrac_M", y = "PFSfrac_M",
           size = 0.5,
           show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of Methionine",
           ylab = "Mut Fraction of Methionine") +
   geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 0.2) + 
  ylim(0, 0.2) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction of Methionine.pdf", width = 6, height = 5)
```

```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSfrac_K", y = "PFSfrac_K",
           size = 0.5,
           show.legend.text = F,
           show.legend = F, 
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of Lysine",
           ylab = "Mut Fraction of Lysine") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
  xlim(0, 1) + 
  ylim(0, 1) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Fraction of Lysine.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSFracPos",
           size = 0.5,
           show.legend.text = T,
           show.legend = T, 
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Positive aa") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) + 
  gghighlight(((PFSFracPos) >= 0.15) & ((PFSseqLength) > 20)  )
pmain
ggsave(pmain, file = "Length vs Fraction of Positive.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSMeanNetCharge",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Mean of charge") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) + 
  gghighlight(((PFSMeanNetCharge) >= 0.15) & ((PFSseqLength) > 20)  )
pmain
ggsave(pmain, file = "Length vs Mean of charge.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSfrac_R",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Arginine") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
  gghighlight(((PFSfrac_R) >= 0.15) & ((PFSseqLength) > 20)  )
pmain
ggsave(pmain, file = "Length vs Fraction of R.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSfrac_acidic",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of acidic aa") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Fraction of acidic.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSfrac_aromatic",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of aromatic aa") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Fraction of aromatic.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSFracNeg",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Negative aa") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Fraction of Negative.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSFracDisoPromoting",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Disorder Promoting aa") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0.2, 1) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Fraction of Disorder Promoting.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSfrac_L",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Leucine") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Fraction of Leucine.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSfrac_M",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Methionine") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.2) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Fraction of Methionine.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSfrac_K",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Lysine") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 1) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Fraction of Lysine.pdf", width = 5, height = 5)

```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSfrac_A", y = "PFSfrac_A",
           size = 0.5,
            show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Fraction of Alanine",
           ylab = "Mut Fraction of Alanine") +
    geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2, show.legend = F,show.legend.text = F) +
    xlim(0, 0.6) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH,
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
  pmain
ggsave(pmain, file = "Fraction of Alanine.pdf", width = 6, height = 5)
```

```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSfrac_A",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Alanine") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 0.6) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Fraction of Alanine.pdf", width = 5, height = 5)
```

```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSmean_hydropathy", y = "PFSmean_hydropathy",
           size = 0.5,
            show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Mean of hydrophobicity",
           ylab = "Mut Mean of hydrophobicity") +
  geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2, show.legend = F,show.legend.text = F) +
    xlim(-4.5, 4.5) + 
  ylim(-4.5, 4.5) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Mean of hydrophobicity.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS2, x = "WTPFSuversky_hydropathy", y = "PFSuversky_hydropathy",
           size = 0.5,
            show.legend.text = F,
            show.legend = F,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Wt Normalized Mean of hydrophobicity",
           ylab = "Mut Normalized Mean of hydrophobicity") +
  geom_abline(intercept = 0, slope = 1, size = 0.5) +
  geom_point(data = dfFSH, color = "coral1", size = 2, show.legend = F,show.legend.text = F) +
    xlim(0, 1) + 
  ylim(0, 1) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )
pmain
ggsave(pmain, file = "Norm Mean of hydrophobicity.pdf", width = 6, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSmean_hydropathy",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Mean of hydrophobicity") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(-4.5, 4.5) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Mean of hydrophobicity.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "PFSfrac_A",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of Alanine") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 1) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "Length vs Norm Mean of hydrophobicity.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "Fraction_of_mutated_IDR",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut Fraction of mutated IDR") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 1) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
pmain
ggsave(pmain, file = "PFS Length vs Fraction_of_mutated_IDR.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "WTIDRLength", y = "Fraction_of_mutated_IDR",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "WT Length of IDR aa",
           ylab = "Mut Fraction of mutated IDR") +
    xlim(0, 800) + 
  ylim(0, 1) +
  gghighlight(((IDRLength) > 20)) +
  
  geom_point(data = dfFSH, color = "coral1", size = 2) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )

pmain
ggsave(pmain, file = "WT IDR Length vs Fraction_of_mutated_IDR.pdf", width = 5, height = 5)

pmain <- ggscatter(dfFS, x = "IDRLength", y = "Fraction_of_mutated_IDR",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "MUT Length of IDR aa",
           ylab = "Mut Fraction of mutated IDR") +
    xlim(0, 800) + 
  ylim(0, 1) +
  gghighlight(((IDRLength) > 20)) +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      )

pmain
ggsave(pmain, file = "Mut IDR Length vs Fraction_of_mutated_IDR.pdf", width = 5, height = 5)
```
```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "WTIDRLength",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut IDR lenth") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 400) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "WT IDRLength vs PFSseqLength.pdf", width = 5, height = 5)
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "IDRLength",
           size = 0.5,
           color = "Pathogenic",
           ggtheme = theme_bw(),
           palette = c("gray20", "#33b3cc"),
           xlab = "Length of Post-frameshift aa",
           ylab = "WT IDR lenth") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 400) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "MUT IDRLength vs PFSseqLength.pdf", width = 5, height = 5)
```

```{r}
pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "WTIDRLength",
           size = 0.5,
           color = "Fraction_of_mutated_IDR",
           ggtheme = theme_bw(),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut IDR lenth") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 400) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "WT IDRLength vs PFSseqLength_color.pdf", width = 5, height = 5)


pmain <- ggscatter(dfFS, x = "PFSseqLength", y = "IDRLength",
           size = 0.5,
           color = "Fraction_of_mutated_IDR",
           ggtheme = theme_bw(),
           xlab = "Length of Post-frameshift aa",
           ylab = "Mut IDR lenth") +
  geom_point(data = dfFSH, color = "coral1", size = 2) +
    xlim(0, 400) + 
  ylim(0, 400) +
  geom_label_repel(data = dfFSH, 
    aes(label = gene_symbol),
    size = 3.5,
    box.padding = 1,
    min.segment.length = 0,
    max.overlaps = Inf,
    color = "coral1",
    show.legend = F,
    show.legend.text = F) +
  theme(aspect.ratio=1,
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()
      ) +
  gghighlight(((PFSseqLength) > 20))
pmain
ggsave(pmain, file = "MUT IDRLength vs PFSseqLength_color.pdf", width = 5, height = 5)
```